/* AUTO-GENERATED by scripts/gen-block-library.js from the v3 design blocks.
   The app's catalog of reusable blocks: key, slug, role, label, editable
   copy defaults. Re-run the generator after a design refresh. */
'use strict';

const BLOCKS = [
  { key:"collision", slug:"hero-collision", role:"hero", label:"Hero — Risk collision",
    fields: { eyebrow:"Spot delivery risks early", headline:"See what could delay delivery before it does.", body:"Quely’s AI reads across the conversations, meetings, work items, and dependencies in your Quely Space to reveal blockers, the work they affect, and where action is needed." } },
  { key:"thread", slug:"hero-thread", role:"hero", label:"Hero — Decision thread",
    fields: { eyebrow:"One searchable history for every piece of work", headline:"Find what was decided and why in minutes.", body:"Quely gives every task a Space where your team can discuss the work, make decisions, and move from async discussion to a live meeting when needed. Quely’s AI assistant, Orbit, makes it easy to retrieve what was decided, why, the trade-offs considered, and who owns the next step." } },
  { key:"bottleneck", slug:"hero-bottleneck", role:"hero", label:"Hero — Knowledge bottleneck",
    fields: { eyebrow:"Preserve project history", headline:"Let anyone understand any task or project without relying on the person who built it.", body:"Quely keeps the decisions, rationale, discussions, meeting transcripts, and supporting documents around any task or project in one Space. Orbit makes that history easy to retrieve, so new engineers can understand why the system works the way it does, what was ruled out, and what comes next." } },
  { key:"handoff", slug:"hero-handoff", role:"hero", label:"Hero — Action handoff",
    fields: { eyebrow:"Turn discussions into action items", headline:"Extract next steps from every conversation and meeting.", body:"Orbit, Quely’s AI assistant, reads the conversations and meeting transcripts in each Space, identifies decisions, follow-ups, and action items, and lets you push the tasks you choose into your project management tool in one click." } },
  { key:"converge", slug:"space-converge", role:"body", label:"Space converge",
    fields: { eyebrow:"One Space for the whole task", headline:"Understand what any task requires without searching across multiple tools.", body:"Get a Space for every task where conversations, decisions, dependencies, supporting documents, and assets stay connected, so anyone can quickly find the information they need to move the work forward." } },
  { key:"anatomy", slug:"space-anatomy", role:"body", label:"Space anatomy",
    fields: { eyebrow:"Inside a Quely Space", headline:"See the work and everything that explains it in one Space.", body:"Each Space keeps the work item alongside the conversations, decisions, meeting records, dependencies, documents, and designs around it. Your team can discuss the work, add updates, and ask Orbit questions from the same place." } },
  { key:"relmap", slug:"relationship-map", role:"body", label:"Relationship map",
    fields: { eyebrow:"Relationships", headline:"See what else could be affected before you make a change.", body:"View the tasks and projects connected to the work, so you can spot dependencies, understand blockers, and see the downstream impact of a change." } },
  { key:"multitool", slug:"multi-tool-space", role:"body", label:"Multi-tool space",
    fields: { eyebrow:"One Space across your project tools", headline:"Bring every team’s part of the project into one place.", body:"Pull work from the tools each team uses into a Space, so everyone can see the full project, discuss the work, schedule meetings, and find what they need in one place." } },
  { key:"beforeafter", slug:"before-after", role:"body", label:"Before / after",
    fields: { eyebrow:"Before Quely / With Quely", headline:"Stop searching across tools to understand the work.", body:"Quely connects each work item to the discussions, meetings, documents, decisions, dependencies, and updates around it, so the team can find the information it needs from one Space." } },
  { key:"howitworks", slug:"how-it-works", role:"body", label:"How it works",
    fields: { eyebrow:"How Quely works", headline:"How work moves through Quely", body:"Bring in the work, discuss it in one Space, meet when needed, and keep every outcome searchable." } },
  { key:"record", slug:"decision-record", role:"body", label:"Decision record",
    fields: { eyebrow:"How Quely keeps it", headline:"", body:"Everything around the work, like discussions, meeting recordings, docs, and more, is in one place, so decisions are easy to find. If you need something specific, our AI assistant Orbit can retrieve it in seconds." } },
  { key:"planning", slug:"sprint-planning", role:"body", label:"Sprint planning",
    fields: { eyebrow:"One searchable space for the sprint", headline:"Plan, commit, and run the sprint with the full history behind every decision.", body:"Review the work, debate estimates, uncover blind spots, assign tasks against actual availability, and keep every decision connected to the sprint. Orbit makes it easy to retrieve why a task received its estimate, what changed, who owns it, and where capacity is tight before the team commits." } },
  { key:"roles", slug:"team-roles", role:"body", label:"Team roles",
    fields: { eyebrow:"One shared view for the whole team", headline:"Give everyone the information they need to move the work forward.", body:"" } },
  { key:"lenses", slug:"orbit-lenses", role:"body", label:"Orbit lenses",
    fields: { eyebrow:"Make every discussion useful", headline:"Know what was decided, what is still open, and what needs to happen next.", body:"Orbit, Quely’s AI assistant, turns the conversations and meeting notes in each Space into a clear view of decisions, risks, open questions, opportunities, action items, and next steps. Schedule a meeting around any item or push it into your project-management tool, so you can move from discussion to action instantly." } },
  { key:"ctaFrag", slug:"cta-fragmentation", role:"cta", label:"CTA — Fragmentation",
    fields: { eyebrow:"See Quely with your own work", headline:"Keep everything around the work in one place.", body:"Discuss the work, add the docs and links behind it, and schedule meetings from the same Space so when someone needs context later, they can find it without searching across different tools." } },
  { key:"ctaDec", slug:"cta-decisions", role:"cta", label:"CTA — Decisions",
    fields: { eyebrow:"See Quely with your own work", headline:"See what was decided and why", body:"Quely gives you a Space for any task and the context around it, so you can easily see what was decided, why, what options were considered, and who owns the next step." } },
  { key:"ctaRisk", slug:"cta-risks", role:"cta", label:"CTA — Risks",
    fields: { eyebrow:"Spot risks early", headline:"See what could slow the project down before it does.", body:"Orbit, Quely's AI Assistant, looks across the work and the context in your Space to surface blockers, dependencies, and action items that need attention." } },
  { key:"ctaKnow", slug:"cta-knowledge", role:"cta", label:"CTA — Knowledge",
    fields: { eyebrow:"Project context", headline:"Make it easy for anyone to get up to speed without asking around.", body:"Keep discussions, docs, meetings, and decisions around the work in one Space, so someone joining later can understand what happened, why, and where things stand without searching across tools or asking someone to explain it." } },
  { key:"ctaAction", slug:"cta-action", role:"cta", label:"CTA — Action",
    fields: { eyebrow:"Decisions & next steps", headline:"Turn discussions into clear next steps.", body:"Orbit, Quely’s AI assistant, surfaces decisions, open questions, risks, and action items from the conversations around the work, so everyone knows what needs to happen next." } },
];

const BY_KEY = {}; const BY_SLUG = {};
BLOCKS.forEach(function (b) { BY_KEY[b.key] = b; BY_SLUG[b.slug] = b; });
// Rule sets may reference a hero key with no servable block; map to a real one.
const KEY_ALIAS = { scatter: 'collision' };
function resolveKey(key) { return KEY_ALIAS[key] || key; }
function get(key) { return BY_KEY[resolveKey(key)] || null; }
function editableFields(entry) {
  const f = (entry && entry.fields) || {};
  return ['eyebrow', 'headline', 'body'].filter(function (k) { return f[k] && f[k].length; });
}
module.exports = { BLOCKS: BLOCKS, BY_KEY: BY_KEY, BY_SLUG: BY_SLUG, KEY_ALIAS: KEY_ALIAS, resolveKey: resolveKey, get: get, editableFields: editableFields };
